### PR TITLE
Features: Leases documentation

### PR DESCRIPTION
**Pull request by Anuradha-Talur**
Signed-off-by: Poornima G <pgurusid@redhat.com>
Signed-off-by: Anuradha Talur <atalur@redhat.com>

### CODE REVIEW

**Comment by shravantc** [comment]
@Anuradha-Talur , I have merged the above file as you can see. Is "Leases" a new feature? If yes in which version?. 
This is because I have to also make an entry into the index page and configuration file

-shravantc

**Comment by Anuradha-Talur** [comment]
@poornimag Will be able to answer this better. She is the one working on it.

**Comment by shravantc** [comment]
thanks @Anuradha-Talur .
@poornimag It would be great , if you can go through the current index file (https://github.com/gluster/glusterdocs/blob/master/Features/README.md) and suggest where "Leases" can fit the best.


PS: yo can also send a PR by adding an entry to index.
thanks,
-shravantc

**Comment by poornimag** [comment]
@shravantc  Leases is a new feature still under review, and is not available for use, while we work on this feature we also added a doc file, we still have not decided in which release the Leases will be released. Will send a PR, once the documentation is finalized.

Thank You

**Comment by shravantc** [comment]
Thanks @poornimag .

**Pull request merged**
