### PR TITLE
Move Install-Guide/compiling-rpms.md to Developer-guide/compiling-rpms.md

### PR DESCRIPTION
**Pull request by kshithijiyer**
Fixes: #536

### CODE REVIEW

**Comment by sankarshanmukhopadhyay** [comment]
Who is looking into addressing the issue and merging this?

**Comment by kshithijiyer** [comment]
> mostly this needs change in mkdocs.yml too?

Yup! Thanks for pointing out.

**Comment by kshithijiyer** [comment]
@sankarshanmukhopadhyay @amarts can you revisit this patch so that we can close it and the associated issue?

**Comment by harigowtham** [comment]
@kshithijiyer The top level changes look fine. The other reason behind the issue is to make the necessary changes inside the compiling guide. The doc is years old and we don't even support the versions that are mentioned in the doc. A portion of this can be fixed by changing the versions mentioned. Also, I'm not sure if there are any other things that cause the steps mentioned in the doc to fail compiling RPMs. This is something we need to try with the latest version of Gluster on various distributions and verify they are upto date. Else it will need some one from build to see what are the changes required. Please feel free to take up as much as possible. We will guide you if you need something. 

Thanks, 
Hari.

**Comment by kshithijiyer** [comment]
@harigowtham I feel it would be better if we update the content in another pr as it would be easier for us to track the changes at a later date. Would that be okay?

**Comment by harigowtham** [comment]
@kshithijiyer I'm fine with the suggested approach. For now we will merge this. Don't want a Doc patch to be this delayed. Please do reopen the issue or create a new one closing this, so we will be able to track the issue. Thanks for the patch!

**Pull request merged**
