### PR TITLE
minor tweaks to the document

### PR DESCRIPTION
**Pull request by sankarshanmukhopadhyay**
small set of tweaks to the document

### CODE REVIEW

**Comment by humblec** [comment]
@sankarshanmukhopadhyay can you revisit the patch and resolve conflict?

**Comment by sankarshanmukhopadhyay** [comment]
https://lists.gluster.org/pipermail/maintainers/2018-August/004900.html

**Comment by prashanthpai** [comment]
> https://lists.gluster.org/pipermail/maintainers/2018-August/004900.html

It has been pointed out earlier that the PR needs to be rebased for the tests to pass. Unfortunately, rebasing and fixing merge conflicts can't be done from the GitHub UI. If you wish to rebase it, you'll have to do it over commandline. If for some reason, using commandline (git) isn't feasible, you can close this PR and reopen a fresh one with the same changes using GitHub UI.

**Comment by sankarshanmukhopadhyay** [comment]
I'm afraid that work on this will have to be held in abeyance. There is a clutch of other stuff to complete after which I'll come back here.

**Pull request closed without merging**
