### PR TITLE
add architecture diagram showing various xlators

### PR DESCRIPTION
**Pull request by itisravi**
Architecture diagram with a small explanation as requested by @msaju
Signed-off-by: Ravishankar N <ravishankar@redhat.com>

### CODE REVIEW

**Review by amarts — APPROVED** [review]

**Comment by itisravi** [comment]
Hi @amarts, would you know off hand what needs to be done for https://gluster.readthedocs.io to pick up changes from `main` branch rather than `master` ?

**Comment by aravindavk** [comment]
> Hi @amarts, would you know off hand what needs to be done for https://gluster.readthedocs.io to pick up changes from `main` branch rather than `master` ?

I think it is `edit_uri` settings to `mkdocs.yml` file. https://www.mkdocs.org/user-guide/configuration/

```
edit_uri: edit/main/docs
```

or 

```
edit_uri: blob/main/docs
```

**Comment by amarts** [comment]
I guess this is to be done by one of the maintainers @ https://readthedocs.org/projects/gluster (@mscherer see if you can help)... 

Goto 'Settings -> Advanced Settings -> change default branch'.

(Also good time to change the set of maintainers there).

**Comment by itisravi** [comment]
@mscherer @deepshikhaaa could you please help with :point_up: ?

**Comment by mscherer** [comment]
yep, I have admin access, let me see.

**Comment by mscherer** [comment]
ok so I changed that on https://readthedocs.org/dashboard/gluster/advanced/ 

I am also adding deepshika as a admin. What should I do for the others:
```
nigelbabu
Humble
schandra
misc
ppai
shaunm
nbalacha
```

**Comment by mscherer** [comment]
I added @amarts and @deepshikhaaa  as admin as well

**Comment by amarts** [comment]
> What should I do for the others:

Normally, we can remove anyone not active for more than 18-24 months from any 'admin' list for sure. Feel free to remove them from there.

**Pull request merged**
