### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
minor typo fix , trying to making some changes in gluster docs :)

### CODE REVIEW

**Comment by humblec** [comment]
Developer docs wil be maintained via gluster source, so not merging this PR

**Comment by SaravanaStorageNetwork** [comment]
:) just trying to push minor typo in existing document to see how glusterdocs works.

**Comment by humblec** [comment]
if that is the case, please concentrate on user documentation :). I can merge the pull request :)

**Comment by SaravanaStorageNetwork** [comment]
:) got it..

**Pull request closed without merging**
