### PR TITLE
Some of the packages necessary for the build on CentOS7 are in the ep…

### PR DESCRIPTION
**Pull request by hunter86bg**
…el release

### CODE REVIEW

**Comment by kalebskeithley** [comment]
AFAICT the only package that's needed to build on CentOS that isn't in CentOS7 and earlier is userspace-rcu and userspace-rcu-devel.

GlusterFS Packages are built in the CentOS Build System (CBS) for the CentOS Storage SIG without using EPEL; userspace-rcu is provided by the Storage SIG.

userspace-rcu is in CentOS 8. I would prefer to see a better explanation of what is needed and where it can be obtained.

**Comment by hunter86bg** [comment]
CentOS SIG packages are built without the '--enable-gnfs', and some of the dependencies are failing due to epel not being enabled.

**Comment by kalebskeithley** [comment]
> CentOS SIG packages are built without the '--enable-gnfs',

irrelevant

> and some of the dependencies are failing due to epel not being enabled.

I would prefer to see a better explanation of exactly what is needed (i.e. "missing"), and where it can be obtained, e.g. EPEL or the Storage SIG.

**Comment by aravindavk** [comment]
@hunter86bg you can add a separate note to enable gNFS. For example, (Mention of dependencies would be useful too)

Additional dependencies are required to enable gNFS and `epel-release` needs to be enabled.

```
# yum install epel-release
```

**Comment by hunter86bg** [comment]
```
[root@servera yum.repos.d]# yum install --assumeno autoconf automake bison cmockery2-devel dos2unix flex   \
>     fuse-devel glib2-devel libacl-devel libaio-devel libattr-devel    \
>     libcurl-devel libibverbs-devel librdmacm-devel libtirpc-devel     \
>     libtool libxml2-devel lvm2-devel make openssl-devel pkgconfig     \
>     pyliblzma python-devel python-eventlet python-netifaces           \
>     python-paste-deploy python-simplejson python-sphinx python-webob  \
>     pyxattr readline-devel rpm-build sqlite-devel systemtap-sdt-devel \
>     tar userspace-rcu-devel | grep "No package"
No package cmockery2-devel available.
No package python-eventlet available.
No package python-paste-deploy available.
No package python-simplejson available.
No package userspace-rcu-devel available.
```
Afterwards "# ./configure --without-libtirpc" leads to :
```
checking for readline in -lreadline -ltermcap... yes
checking for readline in -lreadline -lncurses... yes
checking for io_setup in -laio... yes
checking for URCU... no
checking urcu-bp.h usability... no
checking urcu-bp.h presence... no
checking for urcu-bp.h... no
configure: error: liburcu-bp not found
[root@servera glusterfs]# echo $?
1
```
Rerunning the yum after enabling epel:
```
Dependencies Resolved

================================================================================================================================================================================================
 Package                                           Arch                                 Version                                                      Repository                            Size
================================================================================================================================================================================================
Installing:
 cmockery2-devel                                   x86_64                               1.3.8-2.el7                                                  epel                                  11 k
 python-paste-deploy                               noarch                               1.5.0-10.el7                                                 epel                                  45 k
 python2-eventlet                                  noarch                               0.18.4-1.el7                                                 epel                                 252 k
 python2-simplejson                                x86_64                               3.10.0-2.el7                                                 epel                                 188 k
 userspace-rcu-devel                               x86_64                               0.7.16-1.el7                                                 epel                                  48 k
Installing for dependencies:
 cmockery2                                         x86_64                               1.3.8-2.el7                                                  epel                                  32 k
 pyOpenSSL                                         x86_64                               0.13.1-4.el7                                                 base                                 135 k
 python-greenlet                                   x86_64                               0.4.2-4.el7                                                  extras                                27 k
 python-paste                                      noarch                               1.7.5.1-9.20111221hg1498.el7                                 base                                 866 k
 python-tempita                                    noarch                               0.5.1-6.el7                                                  base                                  33 k
 userspace-rcu                                     x86_64                               0.7.16-1.el7                                                 epel                                  73 k

Transaction Summary
================================================================================================================================================================================================
Install  5 Packages (+6 Dependent packages)
```
After adding the 5 packages from epel the configure is successful:
```

config.status: creating tools/setgfid2path/src/Makefile
config.status: creating tests/env.rc
config.status: creating config.h
config.status: creating site.h
config.status: executing depfiles commands
config.status: executing libtool commands

GlusterFS configure summary
===========================
FUSE client          : yes
epoll IO multiplex   : yes
fusermount           : yes
readline             : yes
georeplication       : yes
Linux-AIO            : yes
Enable Debug         : no
Enable ASAN          : no
Enable TSAN          : no
Use syslog           : yes
XML output           : yes
Unit Tests           : no
Track priv ports     : yes
POSIX ACLs           : yes
SELinux features     : yes
firewalld-config     : no
Events               : yes
EC dynamic support   : x64 sse avx
Use memory pools     : yes
Nanosecond m/atimes  : yes
Server components    : yes
Legacy gNFS server   : no
IPV6 default         : no
Use TIRPC            : no
With Python          : 2.7
Cloudsync            : yes
Link with TCMALLOC   : no

[root@servera glusterfs]# echo $?
0
```

For me it seems that epel is Mandatory and optional.

**Pull request closed without merging**
