### PR TITLE
remove the hadoop guide

### PR DESCRIPTION
**Pull request by mscherer**
The doc do not bring any value, do not link to the latest
version of the connector and point to long gone URL for 3.3.

### CODE REVIEW

**Comment by humblec** [comment]
@mscherer Arent we still support this ? Let me check with @vbellur

**Comment by humblec** [comment]
@vbellur do you agree to remove this ?

**Comment by amarts** [comment]
Ack! 👍

**Comment by humblec** [comment]
Thanks @amarts !

**Pull request merged**
