### PR TITLE
Fix typos in Gluster-On-ZFS.md

### PR DESCRIPTION
**Pull request by bert-willekens**
Fixed typo.

### CODE REVIEW

**Review by aravindavk — APPROVED** [review]

**Comment by Sheetalpamecha** [comment]
The changes looks good. But the base branch should be 'main' instead of 'master'

**Comment by kshithijiyer** [comment]
Apart from sending it to `main` instead of `master` branch,  please do consider updating the commit message to ` Fix typos in Gluster-On-ZFS.md` from `Update Gluster-On-ZFS.md` as the present one isn't very clear.

**Comment by bert-willekens** [comment]
Changed the branch which results in more commits being added to the PR.
Is there any CONTRIBUTING available in regards to which branches to use?

**Comment by kshithijiyer** [comment]
> Changed the branch which results in more commits being added to the PR.
> Is there any CONTRIBUTING available in regards to which branches to use?

Mostly you'll need rebase your main branch as it's outdated and there were patches which got merged which is causing it. For now you can do a rebase and drop the commits which got added by squashing them.

**Pull request merged**
