### PR TITLE
Added a note for quota in upgrade procedure

### LINKED ISSUE #608: Update the upgrade guidelines if quota is enabled
The upgrade procedure needs to be updated if the quota is enabled before upgrading the cluster and if the upgrade is from a version < 7 to a version > 7, as there have been some changes in the checksum calculation procedure which cause the nodes to go into the rejected state, so to fix that the nodes have to be restarted if the op-version is updated to the latest one after upgrading all the nodes so as to update the checksum values for the quota volumes in all the peers.

Please find more details about the issue here : https://github.com/gluster/glusterfs/issues/1332

### PR DESCRIPTION
**Pull request by nik-redhat**
Added a note about how to fix the issue caused by the change
in checksum computation while upgrading from a version less than 7.0

This PR fixes #608 

Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by sankarshanmukhopadhyay** [comment]
Is Gluster 7.0 a version or a release? Or, are these terms synonyms?

**Comment by nik-redhat** [comment]
> Is Gluster 7.0 a version or a release? Or, are these terms synonyms?

We can consider it as synonyms.

**Comment by nik-redhat** [comment]
@sankarshanmukhopadhyay are we good to move ahead with this PR?

**Comment by nik-redhat** [comment]
Thank you @sankarshanmukhopadhyay :)

**Pull request merged**
