### PR TITLE
Update the link to server quorum

### PR DESCRIPTION
**Pull request by itisravi**
The original link is not available, so using an archived version.

### CODE REVIEW

**Comment by itisravi** [comment]
@joejulian There is a bunch of stuff that is missing from  the old website. https://bugzilla.redhat.com/show_bug.cgi?id=1365706 tracks this.  If we can have an ETA by which all of it can be moved, that would be great. Otherwise I do not want to wait indefinitely. @amye @nigelbabu

**Comment by prashanthpai** [comment]
> I think we should pull this documentation in rather than point to the wayback archive.

+1 on that.

**Comment by joejulian** [comment]
> If we can have an ETA by which all of it can be moved, that would be great. Otherwise I do not want to wait indefinitely.
Who is supposed to curate all that? Most of it was out of date.

From my perspective and observations not as a developer but as a user and supporter of users, the feature pages which you refer to in bz were mostly incomplete or incorrect and caused more confusion than help. They were often written before the code and had no instructions or invalid instructions.

I have reached out to Amye and will try to get us access to the old wiki, but I would be very wary of importing anything from it without review.

**Comment by itisravi** [comment]
> I have reached out to Amye and will try to get us access to the old wiki, but I would be very wary of importing anything from it without review.

Okay, I will resubmit the PR with a new page added for server-quorum and link it from the arbiter page.

**Comment by amye** [comment]
If we want to move things back in from the old wiki, I'm perfectly happy to attempt to wake it up -- but so much of that was not quite what we wanted it to be. 
Should this PR be merged, or are we still waiting on the new page for server-quorum?

**Comment by joejulian** [comment]
This should not. It links to archive.org.

**Pull request closed without merging**
