### PR TITLE
Update glossary.md

### PR DESCRIPTION
**Pull request by bensenq**
fix another format

### CODE REVIEW

**Comment by humblec** [comment]
@nigelbabu please let the maintainers merge the patch.

**Comment by amye** [comment]
Hey, I'm delighted to have @nigelbabu take an interest in documentation. 
If it passes, I think any of us can merge documentation help. 👍  😄

**Comment by nigelbabu** [comment]
@bengland2 Thank you for both patches!

@humblec This patch is way too trivial to need maintainer review. I believe documentation should be owned by *all* of us, rather than just maintainers.

**Comment by prashanthpai** [comment]
Maintainers here do not work exclusively and full time on glusterdocs alone. All of us have other responsibilities to cater to and hence there could be delays in reviews sometime. So any form of help (PRs, issues, reviews, merging etc) from anyone are always welcome and much appreciated. Cheers and keep contributing @nigelbabu :+1:

**Comment by humblec** [comment]
@amye @prashanthpai as you know, there had instances in past where the entire doc structure ( ex: glusterfs-specs) was changed by a PR which got merged by a non maintainer of docs repo. I would like to avoid such scenarios, so the comment. 
@nigelbabu the documentation should be owned by all of us., but I am talking about the repo and its maintenance.   Please note that, nobody stops you to step in as a maintainer, but it should be followed by the process. If everyone started to merge patches its difficult to maintain.

**Pull request merged**
