### PR TITLE
Overview.md has an invalid tag

### PR DESCRIPTION
**Pull request by adityaramteke**
Fixes: #443

### CODE REVIEW

**Comment by nixpanic** [comment]
Thanks!

**Comment by nixpanic** [comment]
@nigelbabu how can we check if the documentation was re-generated? I could not find a job on build.gluster.org that triggers it, so maybe there is an other way?

**Comment by nigelbabu** [comment]
That was strange. We didn't have an RTD build triggered for this merge for some reason. Kicked it off manually and it works now.

**Pull request merged**
