### PR TITLE
feature page: runtime lock validator (lockdep)

### PR DESCRIPTION
**Pull request by vshankar**
Signed-off-by: Venky Shankar <vshankar@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@vshankar , can you please push this feature page to https://github.com/gluster/glusterfs-specs repo ? as per http://www.gluster.org/pipermail/gluster-users/2015-July/022918.html we planning to keep it glusterfs-specs repo .

**Comment by vshankar** [comment]
@humblec https://github.com/gluster/glusterfs-specs/pull/1

**Comment by humblec** [comment]
@vshankar  thanks!

**Comment by humblec** [comment]
As this PR is already part of glusterfs-specs project, I am closing this PR

**Pull request closed without merging**
