### PR TITLE
Update glusterd logfile name

### PR DESCRIPTION
**Pull request by pkalever**
now glusterd log file name changed
from etc-glusterfs-glusterd.vol.log to glusterd.log

### CODE REVIEW

**Comment by pkalever** [comment]
Please review
@atinmu 
@humblec

**Comment by humblec** [comment]
@pkalever Does this have any backward compatibility issue ?

**Comment by atinmu** [comment]
LGTM!

@humblec there is no backward compatibility issue here, its just that post update to 3.9 users will get to see a new log file named as "glusterd.log". The older glusterd log file will still be available in the same log directory.

**Comment by humblec** [comment]
@pkalever @atinmu no objections to merge this in the doc. However we may need more wider communication or some hack to maintain backward compatibility if needed.

**Comment by atinmu** [comment]
It should be 3.9 onwards. @humblec I still don't understand your concern on backward compatibility given I already explained that its not an issue.

**Comment by prashanthpai** [comment]
@humblec I remember this change from vbellur: http://review.gluster.org/#/c/13426/ and it's in 3.9 onwards. Has not been backported to 3.8 and 3.7 as it changes log location.

**Comment by humblec** [comment]
@atinmu there may be different tools implemented based on this log location . For ex: http://docs.fluentd.org/v0.10/articles/collect-glusterfs-logs  (https://github.com/keithseahus/fluent-plugin-glusterfs) , these tools will be broken with this change . Also there may be different docs talk about the previous location for ex: https://wiki.centos.org/SpecialInterestGroup/Storage/gluster-Quickstart .  so, I was trying to point out that, we may need a better communication on this. Also understand we dont have a version specific doc in gluster.readthedocs.org.  As we maintain 3 releases,  the users may end up looking into wrong path. These thoughts caused the concern.

**Comment by atinmu** [comment]
@humblec valid point, I've already asked the release maintainer(s) for 3.9 to highlight this change as part of the release note.

**Pull request merged**
