### PR TITLE
Adding Developer-Guide

### PR DESCRIPTION
**Pull request by bkunal**
This patch adds Developer document alligned
to user and admin in the directory Developer-guide.

Documents copied from developer-gude
"https://github.com/gluster/glusterfs/tree/master/doc/developer-guide"

Developers-Index.md and mkdocs.yml was added to reflect the change.

Signed-off-by: Bipin Kunal <bkunal@redhat.com>

### CODE REVIEW

**Comment by prashanthpai** [comment]
As far as I remember, there was decision[1] made to keep the developer guide only in the source repo and continue maintaining it only there. Readthedocs is only for user and admin documentation. Developers who will have to use the code repo contribute can look at the doc in code repo itself.

https://www.gluster.org/pipermail/gluster-users/2015-July/022918.html

**Comment by nixpanic** [comment]
The files that are being added to the documentation are related to workflows and how developers can start contributing. We need the general documentation that does not go into detail of the sources/structures/... to be easily available.

Some of the developer-guide contents should stay in the main source repository, this pull request does not contain those files.

**Comment by nixpanic** [comment]
:+1: for renaming the "Workflow Guide" to "Contributors Guide". This makes is much easier to add more documents that can help new contributors (not only developers) joining our community.

Thanks Bipin!

**Comment by nixpanic** [comment]
Also, http://review.gluster.org/12576 removes these documents from the Gluster sources. This really helps in getting more structure into the docs.

**Pull request merged**
