### PR TITLE
updating registries and files replacing space and underscore with dash

### PR DESCRIPTION
**Pull request by runejuhl**
This PR is https://github.com/gluster/glusterdocs/pull/447 rebased against master.

Marked as draft as I haven't yet had a chance to compile and make sure that everything works as expected; with such a large single commit I'd be surprised if my rebase is perfectly fine on the first try...

### CODE REVIEW

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
Saw the below warnings. Should we fix them here and then merge ?

```
WARNING -  A relative path to 'Install-Guide/compiling-rpms.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'Upgrade-Guide/upgrade-to-8.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'Upgrade-Guide/upgrade-to-7.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'Upgrade-Guide/upgrade-to-6.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'GlusterFS-Tools/gfind_missing_files.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  Documentation file 'Upgrade-Guide/README.md' contains a link to 'Upgrade-Guide/upgrade_to_5.md' which is not found in the documentation files. 
WARNING -  Documentation file 'Upgrade-Guide/Generic_Upgrade_procedure.md' contains a link to 'Upgrade-Guide/op_version.md' which is not found in the documentation files. 
WARNING -  Documentation file 'Upgrade-Guide/upgrade_to_6.md' contains a link to 'Upgrade-Guide/upgrade_to_4.1.md' which is not found in the documentation files. 
WARNING -  Documentation file 'Upgrade-Guide/upgrade_to_7.md' contains a link to 'Upgrade-Guide/upgrade_to_4.1.md' which is not found in the documentation files. 
```

Btw, PR looks good to me. Thanks for getting it done.

**Comment by runejuhl** [comment]
@amarts now that #614 is merged I have a much quicker turnaround on testing (without the need to cherrypick the change), so I'll try find a bit of free time later today to get these warnings resolved.

**Comment by runejuhl** [comment]
FYI this PR should be good now -- `mkdocs` only has the following things to say:

~~~
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/travis/build/gluster/glusterdocs/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - security.md
  - Administrator-Guide/Accessing-Gluster-from-Windows.md
  - release-notes/geo-rep-in-3.7.md 
INFO    -  Documentation built in 7.68 seconds 
~~~

**Comment by aravindavk** [comment]
URLs looking good now, but changed compared to before. For example, https://docs.gluster.org/en/latest/Administrator%20Guide/Setting%20Up%20Volumes/ is changed to https://docs.gluster.org/en/latest/Administrator-Guide/Setting-Up-Volumes/

Old references and Google search may brake for a few days(For example, an old URL mentioned in issues will get 404. Ref: https://github.com/gluster/glusterdocs/issues/218)

**Pull request merged**
