### PR TITLE
update: registries and files replacing space and underscore with dash.

### LINKED ISSUE #445: We should not use spaces or underscore in repository/file name.
The reason for denying spaces are relatively clear - if a repository name can never have space, then any code generation that generates a reference to the repository never has to apply a quoting rule to the canonical description of the reference and the resulting reference will always be parsed correctly.

For example, repo  '[Administrator Guide](https://github.com/gluster/glusterdocs/tree/master/docs/Administrator%20Guide)', then the  HTTP URL of the repo would have to be generated as https://docs.gluster.org/en/latest/Administrator%20Guide/ which would be generated like https://docs.gluster.org/en/latest/Administrator Guide/ 

However, if spaces are simply not allowed in repository names in the first place, then a literal copy of the canonical repository name https://docs.gluster.org/en/latest/Administrator-Guide/  will always be correct in any context it is used and no-one - GitHub, 3rd party script writers, or yourself - will have to spend any effort to ensure that quoting rules are applied correctly in every circumstance that they may be required.

So, while in principle it would be technically possible to allow spaces in repository names, the primarily aesthetic of doing so probably weren't considered to be worth the significant amount of engineering effort that would be required to support it properly and consistently.

### PR DESCRIPTION
**Pull request by adityaramteke**
**Which issue(s) this PR fixes** 
Fixes #445 

**Special notes for your reviewer**:
Underscores are also generally advised against being used in URL’s, while they’re actually not allowed in a hostname they are allowed in other places.  I don’t see any benefit for allowing spaces or underscores myself, I expect they probably don’t either.

### CODE REVIEW

**Comment by nigelbabu** [comment]
While I agree with you, this is going to create a whole bunch of 404s with existing docs. So I'm going to ask that this pull request be held off for a few days until we can do a 301 redirect at Nginx for spaces to hyphens.

**Comment by nigelbabu** [comment]
Infra bug tracking Nginx redirects: https://github.com/gluster/glusterdocs/pull/447

**Comment by adityaramteke** [comment]
@nigelbabu any status on this?

**Comment by nigelbabu** [comment]
It is going to take time as the infra team are currently a little preoccupied with migrating hosting providers. I anticipate this to be part of the infra hackathon in the next 2 weeks.

**Comment by amarts** [comment]
@adityaramteke sorry for delay in this, can you please rebase the patch? to the latest master?

**Comment by adityaramteke** [comment]
@amarts sure will do that

**Comment by adityaramteke** [comment]
@nigelbabu @nixpanic Let me know if you need anything else here.

**Comment by mscherer** [comment]
So, if I understand correctly, the goal is that we want to remove spaces in filename, because while that's perfectly valid and handled so far, that is seen as adding complexity in some systems (which, I do not know). But in order to do that, we need to add a corner case in our proxy configuration for that specific host ?

Isn't it trading complexity from one side to the other for no meaningful and visible change ?

**Comment by amarts** [comment]
#613 fixed this.

**Pull request closed without merging**
